name: Check

on:
  workflow_dispatch:
  pull_requests:
  push:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Runs on Ubuntu 20.04 - Node.js 16
        uses: actions/checkout@v3
      - name: Setting up environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: Installing dependencies
        run: yarn add -D vuepress@next
      - name: Building
        run: yarn docs:build

